require 'opal/base'
require 'opal/mini'

require 'corelib/string/encoding'
require 'corelib/math'
require 'corelib/complex'
require 'corelib/rational'
require 'corelib/time'
require 'corelib/struct'
require 'corelib/io'
require 'corelib/main'
require 'corelib/dir'
require 'corelib/file'
require 'corelib/process'
require 'corelib/random'
require 'corelib/random/seedrandom.js'

require 'corelib/unsupported'
