require 'corelib/runtime'
require 'corelib/helpers'
require 'corelib/module'
require 'corelib/class'
require 'corelib/basic_object'
require 'corelib/kernel'
require 'corelib/proc'
require 'corelib/error'

require 'corelib/nil_class'
require 'corelib/boolean'
require 'corelib/string'
require 'corelib/regexp'
require 'corelib/match_data'
require 'corelib/constants'

require 'corelib/comparable'
require 'corelib/enumerable'
require 'corelib/enumerator'
require 'corelib/array'
require 'corelib/array/inheritance'
require 'corelib/hash'
require 'corelib/string/inheritance'
<<<<<<< 56209df7f7fb10d220e9b784276adbdc5915bed1
require 'corelib/string/encoding'
=======
require 'corelib/match_data'
require 'corelib/math'
>>>>>>> Add Math module
require 'corelib/number'
require 'corelib/complex'
require 'corelib/rational'
require 'corelib/math'
require 'corelib/method'
require 'corelib/range'
require 'corelib/time'
require 'corelib/struct'
require 'corelib/io'
require 'corelib/main'
require 'corelib/dir'
require 'corelib/file'
require 'corelib/process'

require 'corelib/variables'
require 'corelib/unsupported'
