version: "2"

checks:
  argument-count:
    config:
      threshold: 4
  complex-logic:
    config:
      threshold: 10
  file-lines:
    config:
      threshold: 1000
  method-complexity:
    config:
      threshold: 5
  method-count:
    config:
      threshold: 100
  method-lines:
    config:
      threshold: 30
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
  # similar-code:
  #   config:
  #     threshold: # language-specific defaults. an override will affect all languages.
  # identical-code:
  #   config:
  #     threshold: # language-specific defaults. an override will affect all languages.

plugins:
  rubocop:
    enabled: true
    channel: rubocop-0-53

exclude_patterns:
  - "benchmark/*"
  - "benchmark-ips/*"
  - "build/*"
  - "coverage/*"
  - "docs/*"
  - "examples/*"
  - "tasks/*"
  - "spec/*"
  - "test/*"
  - "vendored-minitest/*"
  - "**/node_modules/*"
  - stdlib/nodejs/js-yaml-3-6-1.js
  - lib/opal/source_map/vlq.rb
  - lib/opal/cli_runners/source-map-support*.js
