%x{
// Generated by CoffeeScript 1.6.3
(function() {
  var OpalNode, extensions, fs, parser, parserFile, source, sourceFile, vm, __path__;
  fs = require('fs');
  __path__ = require('path');
  vm = require('vm');
  // vm.runInThisContext(parser, parserFile);
  OpalNode = (function() {
    function OpalNode() {}
    OpalNode.node_require = require;
    return OpalNode;
  })();

  global.OpalNode = OpalNode;

}).call(this);
}


module Kernel
  def node_require name
    `OpalNode.node_require(#{name})`
  end
end

