##
# Gemfile for opal runtime is kinda special..

# no gemspec (treat like its own app)

# always use opal in parent directory
gem "opal", :path => ".."

# need therubyracer to run tests
gem "therubyracer"

# opal has no dependencies
group :opal do
end

# opal does however use opal-spec in testing mode
group :opal_test do
  gem "opal-spec", :git => "git://github.com/opal/opal-spec.git"
end