require 'bundler'
Bundler.setup

require 'opal'

desc "Build app"
task :build do
  src = File.read 'app.rb'
  js  = Opal.parse src

  File.open('app.js', 'w+') do |out|
    out.write js
  end
end

desc "Make sure opal.js exists"
task :runtime do
  unless File.exist? 'opal.js'
    File.open('opal.js', 'w+') do |out|
      out.write Opal.runtime
    end
  end
end