# Uncomment this line to use the gem version of opal
$:.unshift File.expand_path(File.join('..', '..', '..', 'opalite'), __FILE__)
puts $:

require 'opal'

Opal::Rake::BuilderTask.new do |t|
  t.files = 'browser.rb'
  t.out   = 'browser.js'
end

