# NOTE: run bin/format-filters after changing this file
opal_filter "Process" do
  fails "Process.clock_gettime supports the platform clocks mentioned in the documentation CLOCK_MONOTONIC_RAW_APPROX" # NameError: uninitialized constant Process::CLOCK_MONOTONIC_RAW_APPROX
  fails "Process.clock_gettime supports the platform clocks mentioned in the documentation CLOCK_UPTIME_RAW and CLOCK_UPTIME_RAW_APPROX" # NameError: uninitialized constant Process::CLOCK_UPTIME_RAW
  fails "Process.exec (environment variables) coerces environment argument using to_hash" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -Rbun /Users/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb") Output:
  fails "Process.exec (environment variables) sets environment variables in the child environment" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -Rbun /Users/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb") Output:
  fails "Process.exec (environment variables) unsets environment variables whose value is nil" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -Rbun /Users/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb") Output:
  fails "Process.exec (environment variables) unsets other environment variables when given a true :unsetenv_others option" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -Rbun /Users/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb") Output:
  fails "Process.exec raises Errno::EACCES when passed a directory" # Expected Errno::EACCES but got: ArgumentError ([Process.argv] wrong number of arguments (given 0, expected 1))
  fails "Process.exec raises Errno::EACCES when the file does not have execute permissions" # Expected Errno::EACCES but got: ArgumentError ([Process.argv] wrong number of arguments (given 0, expected 1))
  fails "Process.exec raises Errno::ENOENT for a command which does not exist" # Expected Errno::ENOENT but got: ArgumentError ([Process.argv] wrong number of arguments (given 0, expected 1))
  fails "Process.exec raises Errno::ENOENT for an empty string" # Expected Errno::ENOENT but got: ArgumentError ([Process.argv] wrong number of arguments (given 0, expected 1))
  fails "Process.exec runs the specified command, replacing current process" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -Rbun /Users/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb") Output:
  fails "Process.exec sets the current directory when given the :chdir option" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -Rbun /Users/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb") Output:
  fails "Process.exec with a command array coerces the argument using to_ary" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -Rbun /Users/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb") Output:
  fails "Process.exec with a command array uses the first element as the command name and the second as the argv[0] value" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -Rbun /Users/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb") Output:
  fails "Process.exec with a single argument creates an argument array with shell parsing semantics for whitespace" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -Rbun /Users/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb") Output:
  fails "Process.exec with a single argument subjects the specified command to shell expansion" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -Rbun /Users/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb") Output:
  fails "Process.exec with an options Hash with Integer option keys lets the process after exec have specified file descriptor despite close_on_exec" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -Rbun /Users/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb") Output:   6   true
  fails "Process.exec with an options Hash with Integer option keys maps the key to a file descriptor in the child that inherits the file descriptor from the parent specified by the value" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -Rbun /Users/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb") Output:
  fails "Process.exec with an options Hash with Integer option keys sets close_on_exec to false on specified fd even when it fails" # Expected ["true", "true"] == ["true", "false"] to be truthy but was false
  fails "Process.exec with multiple arguments does not subject the arguments to shell expansion" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -Rbun /Users/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb") Output:
  fails "Process.setproctitle should set the process title" # Expected "" to include "rubyspec-proctitle-test"
  fails "Process::Constants has the correct constant values on BSD-like systems" # NameError: uninitialized constant Process::WUNTRACED
  fails "Process::Constants has the correct constant values on Darwin" # NameError: uninitialized constant Process::RLIM_SAVED_MAX
end
