RUBY_PLATFORM       = 'opal'
RUBY_ENGINE         = 'opal'
RUBY_VERSION        = '2.5.8'
RUBY_ENGINE_VERSION = '1.0.5'
RUBY_RELEASE_DATE   = '2020-12-24'
RUBY_PATCHLEVEL     = 0
RUBY_REVISION       = 0
RUBY_COPYRIGHT      = 'opal - Copyright (C) 2013-2020 Adam Beynon and the Opal contributors'
RUBY_DESCRIPTION    = "opal #{RUBY_ENGINE_VERSION} (#{RUBY_RELEASE_DATE} revision #{RUBY_REVISION})"
