RUBY_PLATFORM       = 'opal'
RUBY_ENGINE         = 'opal'
RUBY_VERSION        = '3.0.1'
RUBY_ENGINE_VERSION = '1.2.0.dev'
RUBY_RELEASE_DATE   = '2021-04-05'
RUBY_PATCHLEVEL     = 0
RUBY_REVISION       = '0'
RUBY_COPYRIGHT      = 'opal - Copyright (C) 2013-2021 Adam Beynon and the Opal contributors'
RUBY_DESCRIPTION    = "opal #{RUBY_ENGINE_VERSION} (#{RUBY_RELEASE_DATE} revision #{RUBY_REVISION})"
