opal_filter "Object#frozen" do
  fails "Array#frozen? returns true if array is frozen"
  fails "Array#frozen? returns false for an array being sorted by #sort"
  fails "Array#unshift raises a RuntimeError on a frozen array when the array is modified"
  fails "Array#unshift raises a RuntimeError on a frozen array when the array would not be modified"
  fails "Array#uniq! doesn't yield to the block on a frozen array"
  fails "Array#uniq! raises a RuntimeError on a frozen array when the array would not be modified"
  fails "Array#uniq! raises a RuntimeError on a frozen array when the array is modified"
  fails "Array#sort! raises a RuntimeError on a frozen array"
  fails "Array#slice! raises a RuntimeError on a frozen array"
  fails "Array#shuffle! raises a RuntimeError on a frozen array"
  fails "Array#shift raises a RuntimeError on an empty frozen array"
  fails "Array#shift raises a RuntimeError on a frozen array"
  fails "Array#reverse! raises a RuntimeError on a frozen array"
  fails "Array#reject! raises a RuntimeError on an empty frozen array"
  fails "Array#reject! raises a RuntimeError on a frozen array"
  fails "Array#push raises a RuntimeError on a frozen array"
  fails "Array#pop passed a number n as an argument raises a RuntimeError on a frozen array"
  fails "Array#pop raises a RuntimeError on an empty frozen array"
  fails "Array#pop raises a RuntimeError on a frozen array"
  fails "Array#insert raises a RuntimeError on frozen arrays when the array would not be modified"
  fails "Array#insert raises a RuntimeError on frozen arrays when the array is modified"
  fails "Array#flatten! raises a RuntimeError on frozen arrays when the array would not be modified"
  fails "Array#flatten! raises a RuntimeError on frozen arrays when the array is modified"
  fails "Array#delete raises a RuntimeError on a frozen array"
  fails "Array#delete_if raises a RuntimeError on an empty frozen array"
  fails "Array#delete_if raises a RuntimeError on a frozen array"
  fails "Array#delete_at raises a RuntimeError on a frozen array"
  fails "Array#compact! raises a RuntimeError on a frozen array"
  fails "Array#clear raises a RuntimeError on a frozen array"
  fails "Array#<< raises a RuntimeError on a frozen array"
  fails "Array#[]= raises a RuntimeError on a frozen array"
end
