opal_filter "fixnum and array size" do
  fails "Array#slice raises a RangeError when the length is out of range of Fixnum"
  fails "Array#slice raises a RangeError when the start index is out of range of Fixnum"

  fails "Array#fill with (filler, index, length) raises an ArgumentError or RangeError for too-large sizes"

  fails "Array#[] raises a RangeError when the length is out of range of Fixnum"
  fails "Array#[] raises a RangeError when the start index is out of range of Fixnum"

  fails "Kernel.Integer returns a Fixnum or Bignum object"
  fails "Kernel#Integer returns a Fixnum or Bignum object"

  fails "String#% supports negative bignums with %u or %d"

  fails "String#to_i with bases parses a String in base 2"
  fails "String#to_i with bases parses a String in base 3"
  fails "String#to_i with bases parses a String in base 4"
  fails "String#to_i with bases parses a String in base 5"
  fails "String#to_i with bases parses a String in base 6"
  fails "String#to_i with bases parses a String in base 7"
  fails "String#to_i with bases parses a String in base 8"
  fails "String#to_i with bases parses a String in base 9"
  fails "String#to_i with bases parses a String in base 10"
  fails "String#to_i with bases parses a String in base 11"
  fails "String#to_i with bases parses a String in base 12"
  fails "String#to_i with bases parses a String in base 13"
  fails "String#to_i with bases parses a String in base 14"
  fails "String#to_i with bases parses a String in base 15"
  fails "String#to_i with bases parses a String in base 16"
  fails "String#to_i with bases parses a String in base 17"
  fails "String#to_i with bases parses a String in base 18"
  fails "String#to_i with bases parses a String in base 19"
  fails "String#to_i with bases parses a String in base 20"
  fails "String#to_i with bases parses a String in base 21"
  fails "String#to_i with bases parses a String in base 22"
  fails "String#to_i with bases parses a String in base 23"
  fails "String#to_i with bases parses a String in base 24"
  fails "String#to_i with bases parses a String in base 25"
  fails "String#to_i with bases parses a String in base 26"
  fails "String#to_i with bases parses a String in base 27"
  fails "String#to_i with bases parses a String in base 28"
  fails "String#to_i with bases parses a String in base 29"
  fails "String#to_i with bases parses a String in base 30"
  fails "String#to_i with bases parses a String in base 31"
  fails "String#to_i with bases parses a String in base 32"
  fails "String#to_i with bases parses a String in base 33"
  fails "String#to_i with bases parses a String in base 34"
  fails "String#to_i with bases parses a String in base 35"
  fails "String#to_i with bases parses a String in base 36"

  fails "Fixnum#<< with n << m returns a Bignum == fixnum_min() * 2 when fixnum_min() << 1 and n < 0"
  fails "Fixnum#<< with n << m returns a Bignum == fixnum_max() * 2 when fixnum_max() << 1 and n > 0"
  fails "Fixnum#<< with n << m returns 0 when m < 0 and m is a Bignum"
  fails "Fixnum#<< with n << m returns 0 when m < 0 and m == p where 2**p > n >= 2**(p-1)"

  fails "Fixnum#>> with n >> m returns a Bignum == fixnum_max() * 2 when fixnum_max() >> -1 and n > 0"
  fails "Fixnum#>> with n >> m returns a Bignum == fixnum_min() * 2 when fixnum_min() >> -1 and n < 0"
  fails "Fixnum#>> with n >> m returns 0 when m is a Bignum"

  fails "Fixnum#- returns a Bignum only if the result is too large to be a Fixnum"
end
