opal_filter "Kernel" do
  fails "Kernel has private instance method Array()"
  fails "Kernel has private instance method Hash()"
  fails "Kernel#Float is a private method"
  fails "Kernel#Float raises a TypeError if #to_f returns an Integer"
  fails "Kernel#Integer calls to_i on Rationals"
  fails "Kernel#Integer is a private method"
  fails "Kernel#Integer returns a Fixnum or Bignum object"
  fails "Kernel#String is a private method"
  fails "Kernel#format is a private method"
  fails "Kernel#sleep accepts a Rational"
  fails "Kernel#sleep is a private method"
  fails "Kernel#sleep pauses execution indefinitely if not given a duration"
  fails "Kernel#sprintf is a private method"
  fails "Kernel#to_s returns a tainted result if self is tainted"
  fails "Kernel#to_s returns an untrusted result if self is untrusted"
  fails "Kernel#warn is a private method"
  fails "Kernel.Float raises a TypeError if #to_f returns an Integer"
  fails "Kernel.Integer calls to_i on Rationals"
  fails "Kernel.Integer returns a Fixnum or Bignum object"
end
