opal_filter "language" do
  fails "Magic comment can be after the shebang"
  fails "Magic comment can take Emacs style"
  fails "Magic comment can take vim style"
  fails "Magic comment determines __ENCODING__"
  fails "Magic comment is case-insensitive"
  fails "Magic comment must be at the first line"
  fails "Magic comment must be the first token of the line"
  fails "Regexps with modifers supports /x (extended syntax)"
  fails "Regexps with modifers supports /o (once)"
  fails "Regexps with modifers invokes substitutions for /o only once"
  fails "Regexps with modifers supports modifier combinations"
  fails "Regexps with modifers supports (?imx-imx) (inline modifiers)"
  fails "Regexps with modifers supports (?imx-imx:expr) (scoped inline modifiers)"
  fails "Regexps with modifers supports ASII/Unicode modifiers"
  fails "The defined? keyword for pseudo-variables returns 'expression' for __ENCODING__"
  fails "The defined? keyword when called with a method name having a module as receiver returns nil if the method is private"
  fails "The defined? keyword when called with a method name having a module as receiver returns nil if the method is protected"
  fails "The private keyword changes the visibility of the existing method in the subclass"
  fails "The private keyword changes visibility of previously called method"
  fails "The private keyword changes visiblity of previously called methods with same send/call site"
  fails "The private keyword is overridden when a new class is opened"
  fails "The private keyword marks following methods as being private"
end
