opal_unsupported_filter "MatchData" do
  fails "MatchData#begin returns nil when the nth match isn't found"
  fails "MatchData#begin returns the offset for multi byte strings"
  fails "MatchData#begin returns the offset of the start of the nth element"
  fails "MatchData#end returns nil when the nth match isn't found"
  fails "MatchData#end returns the offset for multi byte strings"
  fails "MatchData#end returns the offset of the end of the nth element"
  fails "MatchData#names equals Regexp#names"
  fails "MatchData#names returns an Array"
  fails "MatchData#names returns each name only once"
  fails "MatchData#names returns the names of the named capture groups"
  fails "MatchData#names returns [] if there were no named captures"
  fails "MatchData#names sets each element to a String"
  fails "MatchData#offset returns a two element array with the begin and end of the nth match"
  fails "MatchData#offset returns the offset for multi byte strings"
  fails "MatchData#offset returns [nil, nil] when the nth match isn't found"
  fails "MatchData#post_match keeps taint status from the source string"
  fails "MatchData#post_match keeps untrusted status from the source string"
  fails "MatchData#pre_match keeps taint status from the source string"
  fails "MatchData#pre_match keeps untrusted status from the source string"
  fails "MatchData#regexp returns the pattern used in the match"
  fails "MatchData#[Symbol] raises an IndexError if there is no named match corresponding to the String"
  fails "MatchData#[Symbol] raises an IndexError if there is no named match corresponding to the Symbol"
  fails "MatchData#[Symbol] returns matches in the String's encoding"
  fails "MatchData#[Symbol] returns nil on non-matching named matches"
  fails "MatchData#[Symbol] returns the corresponding named match when given a String"
  fails "MatchData#[Symbol] returns the corresponding named match when given a Symbol"
  fails "MatchData#[Symbol] returns the last match when multiple named matches exist with the same name"
  fails "MatchData#[Symbol] returns the matching version of multiple corresponding named match"
  fails "MatchData#begin returns the offset for multi byte strings with unicode regexp"
  fails "MatchData#end returns the offset for multi byte strings with unicode regexp"
  fails "MatchData#offset returns the offset for multi byte strings with unicode regexp"
end
