#!/usr/bin/env ruby

specs = ARGV.map do |s|
  s.end_with?('.rb') ? s : "#{s}/**/*_spec.rb"
end
pattern = %Q{MSPEC_PATTERN="{#{specs.join(',')}}"} if specs.any?
command = [pattern, 'rake mspec'].compact.join(' ')
exec command

# RUBYOPT="-rbundler/setup -rmspec/opal/special_calls" bundle exec mspec run -t opal -pspec/ruby/spec_helper spec/ruby/core/true/*
