autoload :Marshal, 'corelib/marshal'
require 'corelib/string/mutable'
require 'corelib/string/unpack'
require 'corelib/array/pack'
autoload :ObjectSpace, 'corelib/object_space'
require 'corelib/pattern_matching/base'
autoload :PatternMatching, 'corelib/pattern_matching'
autoload :TracePoint, 'corelib/trace_point'
require 'corelib/binding'
