::Object.autoload :FileTest, 'corelib/file_test'
::Object.autoload :Marshal, 'corelib/marshal'
::Object.require 'corelib/string/encoding/dummy'
::Object.require 'corelib/string/encoding/eucjp'
::Object.require 'corelib/string/encoding/jis'
::Object.require 'corelib/string/encoding/sjis'
::Object.require 'corelib/string/unpack'
::Object.require 'corelib/array/pack'
::Object.autoload :ObjectSpace, 'corelib/object_space'
::Object.require 'corelib/pattern_matching/base'
::Object.autoload :PatternMatching, 'corelib/pattern_matching'
::Object.autoload :TracePoint, 'corelib/trace_point'
::Object.require 'io/buffer'
::Object.require 'runtime/platforms/vsvfs'
