require 'opal/base'

require 'corelib/nil'
require 'corelib/boolean'
require 'corelib/string'
require 'corelib/comparable'
require 'corelib/enumerable'
require 'corelib/enumerator'
require 'corelib/array'
require 'corelib/hash'
require 'corelib/number'
require 'corelib/range'
require 'corelib/proc'
require 'corelib/method'
require 'corelib/regexp'
require 'corelib/variables'
require 'corelib/io'
require 'opal/regexp_anchors'
