# NOTE: run bin/format-filters after changing this file
opal_filter "ARGF" do
  fails "ARGF.filename returns the current file name on each file" # Expected ["/home/jan/workspace/opal/spec/ruby/core/argf/fixtures/file1.txt",  "/home/jan/workspace/opal/spec/ruby/core/argf/fixtures/file1.txt",  "/home/jan/workspace/opal/spec/ruby/core/argf/fixtures/file1.txt",  "/home/jan/workspace/opal/spec/ruby/core/argf/fixtures/file2.txt",  "/home/jan/workspace/opal/spec/ruby/core/argf/fixtures/file2.txt",  "/home/jan/workspace/opal/spec/ruby/core/argf/fixtures/file2.txt"] == ["ruby/core/argf/fixtures/file1.txt",  "ruby/core/argf/fixtures/file1.txt",  "ruby/core/argf/fixtures/file1.txt",  "ruby/core/argf/fixtures/file2.txt",  "ruby/core/argf/fixtures/file2.txt",  "ruby/core/argf/fixtures/file2.txt"] to be truthy but was false
  fails "ARGF.fileno returns the current file number on each file" # Expected [Number, Number, Number, Number] == [Integer, Integer, Integer, Integer] to be truthy but was false
  fails "ARGF.getc reads each char of files" # NotImplementedError: String#<< not supported. Mutable String methods are currently not supported in Opal.
  fails "ARGF.gets modifies and backups two files when in place edit mode is on" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -i.bak /home/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb /home/jan/workspace/opal/tmp/rubyspec_temp/file1.txt /home/jan/workspace/opal/tmp/rubyspec_temp/file2.txt") Output:
  fails "ARGF.gets modifies the files when in place edit mode is on" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -i /home/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb /home/jan/workspace/opal/tmp/rubyspec_temp/file1.txt /home/jan/workspace/opal/tmp/rubyspec_temp/file2.txt") Output:
  fails "ARGF.path returns the current file name on each file" # Expected ["/home/jan/workspace/opal/spec/ruby/core/argf/fixtures/file1.txt",  "/home/jan/workspace/opal/spec/ruby/core/argf/fixtures/file1.txt",  "/home/jan/workspace/opal/spec/ruby/core/argf/fixtures/file1.txt",  "/home/jan/workspace/opal/spec/ruby/core/argf/fixtures/file2.txt",  "/home/jan/workspace/opal/spec/ruby/core/argf/fixtures/file2.txt",  "/home/jan/workspace/opal/spec/ruby/core/argf/fixtures/file2.txt"] == ["ruby/core/argf/fixtures/file1.txt",  "ruby/core/argf/fixtures/file1.txt",  "ruby/core/argf/fixtures/file1.txt",  "ruby/core/argf/fixtures/file2.txt",  "ruby/core/argf/fixtures/file2.txt",  "ruby/core/argf/fixtures/file2.txt"] to be truthy but was false
  fails "ARGF.read clears output buffer before appending to it" # NotImplementedError: out_string buffer is currently not supported
  fails "ARGF.read treats second argument as an output buffer" # NotImplementedError: out_string buffer is currently not supported
  fails "ARGF.read_nonblock clears output buffer before appending to it" # NotImplementedError: NotImplementedError
  fails "ARGF.read_nonblock reads a number of bytes from stdin" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal /home/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb < ruby/core/argf/fixtures/stdin.txt") Output:
  fails "ARGF.read_nonblock reads a number of bytes from the first file" # NotImplementedError: NotImplementedError
  fails "ARGF.read_nonblock reads from a single file consecutively" # NotImplementedError: NotImplementedError
  fails "ARGF.read_nonblock reads the contents of a special device file" # NotImplementedError: NotImplementedError
  fails "ARGF.read_nonblock reads up to the given amount of bytes" # NotImplementedError: NotImplementedError
  fails "ARGF.read_nonblock reads up to the given bytes from STDIN" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal /home/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb < ruby/core/argf/fixtures/file1.txt") Output:
  fails "ARGF.read_nonblock reads up to the given bytes from a file when a file and STDIN are present" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal /home/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb ruby/core/argf/fixtures/file1.txt - < ruby/core/argf/fixtures/file2.txt") Output:
  fails "ARGF.read_nonblock treats second argument as an output buffer" # NotImplementedError: NotImplementedError
  fails "ARGF.read_nonblock treats second nil argument as no output buffer" # NotImplementedError: NotImplementedError
  fails "ARGF.read_nonblock when using multiple files reads up to the given amount of bytes from the first file" # NotImplementedError: NotImplementedError
  fails "ARGF.read_nonblock when using multiple files returns an empty String when reading after having read the first file in its entirety" # NotImplementedError: NotImplementedError
  fails "ARGF.read_nonblock with STDIN raises IO::EAGAINWaitReadable when empty" # NameError: uninitialized constant IO::EAGAINWaitReadable
  fails "ARGF.read_nonblock with STDIN returns :wait_readable when the :exception is set to false" # NotImplementedError: NotImplementedError
  fails "ARGF.readline modifies and backups two files when in place edit mode is on" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -i.bak /home/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb /home/jan/workspace/opal/tmp/rubyspec_temp/file1.txt /home/jan/workspace/opal/tmp/rubyspec_temp/file2.txt") Output:
  fails "ARGF.readline modifies the files when in place edit mode is on" # Expected exit status is 0 but actual is 1 for command ruby_exe("bundle exec opal -i /home/jan/workspace/opal/tmp/rubyspec_temp/rubyexe.rb /home/jan/workspace/opal/tmp/rubyspec_temp/file1.txt /home/jan/workspace/opal/tmp/rubyspec_temp/file2.txt") Output:
  fails "ARGF.readpartial clears output buffer before appending to it" # NotImplementedError: out_string buffer is currently not supported
  fails "ARGF.readpartial clears output buffer even if EOFError is raised because @argf is at end" # NotImplementedError: out_string buffer is currently not supported
  fails "ARGF.readpartial treats second argument as an output buffer" # NotImplementedError: out_string buffer is currently not supported
  fails "ARGF.to_i returns the current file number on each file" # Expected [Number, Number, Number, Number] == [Integer, Integer, Integer, Integer] to be truthy but was false
end
