opal_filter "BasicObject" do
  fails "BasicObject does not define built-in constants (according to const_defined?)"
  fails "BasicObject does not define built-in constants (according to defined?)"
  fails "BasicObject instance metaclass contains methods defined for the BasicObject instance"
  fails "BasicObject instance metaclass has BasicObject as superclass"
  fails "BasicObject instance metaclass is an instance of Class"
  fails "BasicObject metaclass contains methods for the BasicObject class"
  fails "BasicObject metaclass has Class as superclass"
  fails "BasicObject raises NameError when referencing built-in constants"
  fails "BasicObject raises NoMethodError for nonexistent methods after #method_missing is removed"
  fails "BasicObject#initialize does not accept arguments"
  fails "BasicObject#instance_eval binds self to the receiver"
  fails "BasicObject#instance_eval evaluates strings"
  fails "BasicObject#instance_eval executes in the context of the receiver"
  fails "BasicObject#instance_eval gets constants in the receiver if a string given"
  fails "BasicObject#instance_eval has access to receiver's instance variables"
  fails "BasicObject#instance_eval makes the receiver metaclass the scoped class when used with a string"
  fails "BasicObject#instance_eval raises a TypeError when defining methods on an immediate"
  fails "BasicObject#instance_eval raises a TypeError when defining methods on numerics"
  fails "BasicObject#instance_eval sets class variables in the receiver"
  fails "BasicObject#instance_eval treats block-local variables as local to the block"
  fails "BasicObject#instance_exec binds the block's binding self to the receiver"
  fails "BasicObject#instance_exec has an arity of -1"
  fails "BasicObject#instance_exec raises a LocalJumpError unless given a block"
  fails "BasicObject#instance_exec raises a TypeError when defining methods on an immediate"
  fails "BasicObject#instance_exec raises a TypeError when defining methods on numerics"
  fails "BasicObject#instance_exec sets class variables in the receiver"
  fails "BasicObject#__send__ has a negative arity"
  fails "Kernel#send has a negative arity"
  fails "Kernel#public_send has a negative arity"
  fails "Module#prepend does not affect the superclass"
  fails "Module#singleton_class? returns true for singleton classes"
end
