opal_filter "Set" do
  fails "Set#& raises an ArgumentError when passed a non-Enumerable"
  fails "Set#& returns a new Set containing only elements shared by self and the passed Enumerable"
  fails "Set#== does not depend on the order of nested Sets"
  fails "Set#== returns true when the passed Object is a Set and self and the Object contain the same elements"
  fails "Set#divide divides self into a set of subsets based on the blocks return values"
  fails "Set#divide when passed a block with an arity of 2 divides self into a set of subsets based on the blocks return values"
  fails "Set#divide when passed a block with an arity of 2 yields each two Object to the block"
  fails "Set#divide yields each Object to the block"
  fails "Set#flatten raises an ArgumentError when self is recursive"
  fails "Set#flatten returns a copy of self with each included Set flattened"
  fails "Set#flatten! flattens self"
  fails "Set#flatten! raises an ArgumentError when self is recursive"
  fails "Set#flatten! returns nil when self was not modified"
  fails "Set#flatten! returns self when self was modified"
  fails "Set#flatten_merge flattens the passed Set and merges it into self"
  fails "Set#flatten_merge is protected"
  fails "Set#flatten_merge raises an ArgumentError when trying to flatten a recursive Set"
  fails "Set#hash is static"
  fails "Set#inspect correctly handles self-references"
  fails "Set#intersection raises an ArgumentError when passed a non-Enumerable"
  fails "Set#intersection returns a new Set containing only elements shared by self and the passed Enumerable"
  fails "Set#keep_if keeps every element from self for which the passed block returns true"
  fails "Set#keep_if returns an Enumerator when passed no block"
  fails "Set#keep_if returns self"
  fails "Set#keep_if yields every element of self"
  fails "Set#merge raises an ArgumentError when passed a non-Enumerable"
  fails "Set#pretty_print passes the 'pretty print' representation of self to the pretty print writer"
  fails "Set#pretty_print_cycle passes the 'pretty print' representation of a self-referencing Set to the pretty print writer"
  fails "Set#reject! deletes every element from self for which the passed block returns true"
  fails "Set#reject! returns an Enumerator when passed no block"
  fails "Set#reject! returns nil when self was not modified"
  fails "Set#reject! returns self when self was modified"
  fails "Set#reject! yields every element of self"
  fails "Set#select! keeps every element from self for which the passed block returns true"
  fails "Set#select! returns an Enumerator when passed no block"
  fails "Set#select! returns nil when self was not modified"
  fails "Set#select! returns self when self was modified"
  fails "Set#select! yields every element of self"
  fails "Set#^ raises an ArgumentError when passed a non-Enumerable"
  fails "Set#^ returns a new Set containing elements that are not in both self and the passed Enumberable"
end
