# Uncomment this line to use the gem version of opal
$:.unshift File.join(File.dirname(__FILE__), '..', '..', 'lib')

require 'opal'

Opal::Rake::BuilderTask.new do |t|
  t.files = 'rquery_demo.rb'
  t.out   = 'rquery_demo.js'
end

