opal_filter "block args" do
  fails "A block allows for a leading space before the arguments"
  fails "A block taking |a, b| arguments assigns 'nil' and 'nil' to the arguments when a single, empty Array is yielded"
  fails "A block taking |a, b| arguments assigns the element of a single element Array to the first argument"
  fails "A block taking |a, b| arguments destructures a single Array value yielded"
  fails "A block taking |a, b| arguments calls #to_ary to convert a single yielded object to an Array"
  fails "A block taking |a, b| arguments does not call #to_ary if the single yielded object is an Array"
  fails "A block taking |a, b| arguments raises an TypeError if #to_ary does not return an Array"
  fails "A block taking |a, *b| arguments assigns 'nil' and '[]' to the arguments when a single, empty Array is yielded"
  fails "A block taking |a, *b| arguments assigns the element of a single element Array to the first argument"
  fails "A block taking |a, *b| arguments destructures a single Array value assigning the remaining values to the rest argument"
  fails "A block taking |a, *b| arguments calls #to_ary to convert a single yielded object to an Array"
  fails "A block taking |a, *b| arguments does not call #to_ary if the single yielded object is an Array"
  fails "A block taking |a, *b| arguments raises an TypeError if #to_ary does not return an Array"
  fails "A block taking |*| arguments does not raise an exception when no values are yielded"
  fails "A block taking |*| arguments does not raise an exception when values are yielded"
  fails "A block taking |*| arguments does not call #to_ary if the single yielded object is an Array"
  fails "A block taking |*| arguments does not call #to_ary if the object does not respond to #to_ary"
  fails "A block taking |*a| arguments does not call #to_ary if the single yielded object is an Array"
  fails "A block taking |a, | arguments assigns nil to the argument when no values are yielded"
  fails "A block taking |a, | arguments assgins the argument a single value yielded"
  fails "A block taking |a, | arguments assigns the argument the first value yielded"
  fails "A block taking |a, | arguments assigns the argument the first of several values yielded when it is an Array"
  fails "A block taking |a, | arguments assigns nil to the argument when passed an empty Array"
  fails "A block taking |a, | arguments assigns the argument the first element of the Array when passed a single Array"
  fails "A block taking |a, | arguments calls #to_ary to convert a single yielded object to an Array"
  fails "A block taking |a, | arguments does not call #to_ary if the single yielded object is an Array"
  fails "A block taking |a, | arguments does not call #to_ary if the object does not respond to #to_ary"
  fails "A block taking |a, | arguments raises an TypeError if #to_ary does not return an Array"
  fails "A block taking |(a, b)| arguments calls #to_ary to convert a single yielded object to an Array"
  fails "A block taking |(a, b)| arguments does not call #to_ary if the single yielded object is an Array"
  fails "A block taking |(a, b)| arguments raises an TypeError if #to_ary does not return an Array"
  fails "A block taking |(a, b), c| arguments assigns nil to the arguments when yielded no values"
  fails "A block taking |(a, b), c| arguments destructures a single one-level Array value yielded"
  fails "A block taking |(a, b), c| arguments destructures a single multi-level Array value yielded"
  fails "A block taking |(a, b), c| arguments calls #to_ary to convert a single yielded object to an Array"
  fails "A block taking |(a, b), c| arguments does not call #to_ary if the single yielded object is an Array"
  fails "A block taking |(a, b), c| arguments does not call #to_ary if the object does not respond to #to_ary"
  fails "A block taking |(a, b), c| arguments raises an TypeError if #to_ary does not return an Array"
  fails "A block taking nested |a, (b, (c, d))| assigns nil to the arguments when yielded no values"
  fails "A block taking nested |a, (b, (c, d))| destructures separate yielded values"
  fails "A block taking nested |a, (b, (c, d))| destructures a single multi-level Array value yielded"
  fails "A block taking nested |a, (b, (c, d))| destructures a single multi-level Array value yielded"
  fails "A block taking nested |a, ((b, c), d)| assigns nil to the arguments when yielded no values"
  fails "A block taking nested |a, ((b, c), d)| destructures separate yielded values"
  fails "A block taking nested |a, ((b, c), d)| destructures a single multi-level Array value yielded"
  fails "A block taking nested |a, ((b, c), d)| destructures a single multi-level Array value yielded"
end
